### ISSUE TITLE
Test harness links only direct includes: a function two include hops away fails to link

### ISSUE THREAD

**Issue by jlaustill** [jlaustill/c-next#1508]
## Summary

An execution fixture whose entry calls a function **two include hops away** fails to
link. The transpiler is not at fault: it emits the definition correctly and the same
three objects link by hand. The harness links a fixture's DIRECT includes only.

Found while adding a regression fixture for #1491, and worked around there by adding a
redundant `#include` to the entry — a workaround recorded in the fixture comment, which is
why this is filed rather than left.

## Reproduction

Three files in one directory:

```cnx
// leaf.cnx
u32 leafValue() { return 5; }

// mid.cnx
#include "leaf.cnx"
u32 viaMid() { return leafValue(); }

// entry.test.cnx
// test-execution
#include "mid.cnx"
u32 main() {
    u32 v <- viaMid();
    if (v != 5) return 1;
    return 0;
}
```

`npm test -- <dir>`:

```
FAIL  entry.test.cnx [C+CPP]
mid.c:(.text+0x9): undefined reference to `leafValue'
collect2: error: ld returned 1 exit status
```

## Attribution — measured, not inferred

| check | result |
| --- | --- |
| `leaf.c` contains the definition | yes — `grep -c 'uint32_t leafValue' leaf.c` → 1 |
| the three objects link by hand | **exit 0** — `gcc -std=c99 -I tests/include -I <dir> entry.test.c mid.c leaf.c` |
| the harness links them | no — `undefined reference` |

So the generated C is correct and complete; only the link step is short.

## Why the existing 4-file fixture does not already cover this

`tests/bugs/issue-1334-scope-declaration-sites/span4-d.test.cnx` is a four-file chain and
passes, which looks like evidence transitive linking works. It is not: `span4-a`/`span4-b`
contribute **types** (`Point`, `Mode`), and the only function called across files,
`Span__fromC`, is defined in `span4-c` — one hop. Nothing in the corpus links a function
two hops away, which is why this has gone unnoticed.

## Why it matters beyond one fixture

CLAUDE.md already records that **35 of 37 error codes have zero cross-file fixtures and
none has a 2+hop one** (#1219). This is one structural reason: an execution fixture that
would exercise a 2-hop chain cannot link, so the harness cannot construct the context.
"A guard you cannot reach is not a guard" — the coverage gap is not only that nobody wrote
those fixtures, but that a whole class of them fails for a reason unrelated to what they
test.

## Where

`scripts/test-utils.ts` — the compile/link step collects the fixture's includes. It needs
the transitive closure, which `DependencyGraph`/`IncludeResolver` already compute for the
transpiler itself.

## Suggested acceptance

The reproduction above passes, plus a negative control: a fixture where the 2-hop file
defines nothing the entry needs must still link (so the fix is not "link every `.c` in the
directory", which would hide a genuinely missing definition).

## Definition of Done

The link defect above is one instance of a broader gap: **ADR-010 owns cross-file
includes and has no scope-context matrix.** Measured on `main` at `15fd3c86`
(2026-09-05):

| fact | value |
| --- | --- |
| `<!-- MATRIX-SEVERITY -->` table in `adr-010-c-interoperability.md` | none |
| fixtures marked `// test-adr: 010` | 0 |
| `AdrProvenance.record("010", …)` sites | 0 |
| ADR-010 section in `docs/scope-context-matrix.md` | none |

So ADR-010 occupies nothing, and the matrix cannot say whether any include pattern is
exercised. The include ADR is exactly the one whose relationship axis (`direct` /
`transitive`) is the thing under test, and it is the one ADR with no row.

This issue is done when **all** of the following hold.

### 1. The harness links the transitive include closure

- `scripts/test-utils.ts` line 1398 builds the link list with `findHelperCnxFiles`
  (direct only). `helperClosure` (line 875) already computes the transitive closure
  for the #1488 scheduler lock and is built on the same primitive. The link step
  consumes the closure. One definition of "helper", not two callers walking it to
  different depths.
- The reproduction above passes as a fixture, marked `// test-adr: 010`.
- **Negative control** as stated in the acceptance: a 2-hop file that defines nothing
  the entry needs still links, so the fix is not "link every `.c` in the directory".
- **Mutation proof:** revert the closure to the direct list and the 2-hop fixture
  fails to link again. Restore, confirm green.
- Widening `helperCnxFiles` also widens the in-place helper re-transpile loop and the
  header-divergence guard to transitive helpers. Read the first full `npm test` for
  divergences that were previously invisible; do not assume clean.
- The redundant `#include "dup-lib.cnx"` in
  `tests/bugs/issue-1491-duplicate-typedef/two-consumers.test.cnx` (PR #1512) is
  removed once this lands and the fixture still links. That removal is the proof the
  workaround was a workaround.

### 2. ADR-010 declares its matrix

Add a `<!-- MATRIX-SEVERITY -->` table to `docs/decisions/adr-010-c-interoperability.md`
following ADR-016/051/057. Declare per cell; an undeclared cell reads as `off` and is a
recorded claim that the cell cannot exist, so each `off` gets a sentence saying why.

Design questions to settle in the ADR text before declaring cells:

- **`same file` is `off` for every context.** An include is cross-file by definition.
  Record that, do not leave it blank.
- **Where does an include fixture occupy?** A `#include` directive sits in no
  declaration, so `FixtureContext.at()` returns null for it, and E0503/E0504/E0507 all
  report at `1:0`, which `FixtureOccupancy.diagnosticLines()` discards (#1235). Every
  rejection fixture will therefore land in "linked fixtures with no derivable
  context". That is acceptable **only if the ADR says so** and the acceptance
  fixtures occupy cells through the *use site*: a call or type use of the included
  symbol inside a `top-level function` / `scope method` / `global variable` /
  `scope member`.
- **Provenance.** Per CLAUDE.md, an ADR with no `AdrProvenance.record` site occupies
  nothing from codegen-only fixtures; only 016 and 057 have one. Decide whether
  ADR-010 records at the point a cross-file symbol resolves through an include (the
  use site above), or whether use-site diagnostics alone are enough. Pick one, write
  it down, and do not do both.
- **#1402 caveat.** The relationship axis measures the *deepest* `.cnx` chain
  reachable from the fixture, not hops to the declaration under test. Build each
  chain fixture so the deepest hop **is** the symbol under test, otherwise a fixture
  exercising a direct symbol with an unrelated 2-hop helper reads as `transitive`.

### 3. Every include pattern ADR-010 promises has a fixture marked `// test-adr: 010`

Existing fixtures gain the marker; missing ones are written. Counted on `main` today:

**Spelling: what the directive says**

| # | pattern | promise | today |
| --- | --- | --- | --- |
| S1 | `#include <x.cnx>` | emits `<x.h>` | `tests/include/include-cnx-basic` (unmarked) |
| S2 | `#include "x.cnx"` | emits `"x.h"` | `tests/include/include-cnx-quoted` (unmarked) |
| S3 | `#include "x.h"` local C header | symbols parsed, passed through | 91 fixtures, none marked |
| S4 | `#include <x.h>` system header | passed through, no validation | 49 fixtures, none marked |
| S5 | `.hpp` in a run that declares C++ | accepted, C++ output | 38 fixtures, none marked |
| S6 | `"sub/x.cnx"` subdirectory | emitted include names the subdirectory (#1467) | 7 fixtures incl. `issue-1134`, none marked |
| S7 | included file **outside** the entry's tree | emitted include stays bare (#1467) | `tests/regression/issue-332-cnx-struct-pointer` reaches `tests/include/issue-332-cnx-types.cnx` via the search path, unmarked, and predates #1467 so it does not assert the bare-name guarantee on purpose. #1467 itself shipped unit tests only. |
| S8 | same basename in two directories | both resolve, no collision (#1134) | `issue-1134-basename-include-collision` |
| S9 | a file including its own header | self-include of public scope | `tests/include/self-include-public-scope` |
| S10 | C and `.cnx` includes mixed in one file | both rewritten correctly | `tests/include/include-cnx-mixed` |

**Graph: how far the symbol is from its use**

| # | pattern | today |
| --- | --- | --- |
| G1 | function / type / scope member one hop away, called or used | many, none marked |
| G2 | **function two hops away, called** | **none** — this issue; cannot link until §1 |
| G3 | type two hops away, used | `issue-1334/span4-d` (types only, unmarked) |
| G4 | diamond: two files include one lib, entry includes both consumers **and** the lib | `issue-1491-duplicate-typedef` on PR #1512 |
| G5 | diamond where the entry does **not** include the shared lib directly | **none** — this is the §1 negative control's sibling; the lib must still link through either consumer |

**Rejection: what the transpiler refuses**

| # | pattern | code | today |
| --- | --- | --- | --- |
| R1 | `#include "x.c"` implementation file | E0503 | `tests/preprocessor/include-impl-file-error` |
| R2 | `.h` / `.hpp` include beside an existing `.cnx` | E0504 | `tests/include/cnx-alternative-error-{angle,quoted,hpp}` + `-no-error` control |
| R3 | C++ header in a run not declaring C++ | E0507 | `tests/include/cpp-undeclared` |
| R4 | quoted `.cnx` that does not exist | **none** | ADR-010 says quoted `.cnx` files are "validated"; `IncludeResolver` emits `Warning: #include "…" not found` and continues. Decide: promote to a diagnostic with a code, or amend the ADR wording (user approval either way). A warning with no code cannot be asserted by a `.expected.error`, so today this promise is unfixtured by construction. |
| R5 | include-guard collision | (#1133) | `issue-1133-guard-collision-diagnostic` |

Each rejection fixture keeps a **negative control** beside it (the R2 `-no-error` shape):
the thing that must stay silent, in the same directory.

### 4. The matrix is regenerated and gated

- `npm run coverage:matrix` writes an ADR-010 section into `docs/scope-context-matrix.md`.
- `npm run coverage:matrix:check` is green: no `**MISSING**` cell for ADR-010.
- The ADR-010 "no derivable context" list contains exactly the R-axis fixtures and
  nothing else. A G- or S-axis fixture appearing there means its use site is missing.

### 5. Every new fixture is mutation-checked

Presence is not proof. For each fixture added or marked: break what it watches, confirm
it goes red, restore, confirm green. Clean generated `.test.c/.h/.cpp/.hpp` between
runs so a mutation that lets a `test-error` fixture compile does not contaminate the
next attribution. Record the table in the PR.

### 6. ADR-010 still passes the rewrite test

The matrix table and the pattern list are language-level statements. No `src/**`
paths, no module names, no line numbers in the ADR. `npm run adr:independence:check`
is green. The table above in *this issue* names files because an issue is allowed to;
the ADR is not.

### Out of scope

- Changing what any include pattern *means*. That is a syntax change and needs its own
  ADR discussion.
- ADR-105 (prefixed includes) — Research, deferred to v2.
- Fixing #1402 (relationship axis measures deepest chain, not hops to declaration).
  Work around it per §2; do not fix it here.

**Comment by jlaustill** [comment]
The per-PR matrix rule this issue's DoD §2–4 works out is now recorded in `CLAUDE.md` by #1513, so it applies to every PR rather than only this one.

**Comment by jlaustill** [comment]
Starting work on branch `fix/1508-transitive-link-closure`.

**Reproduction confirmed, and the attribution in the body re-verified independently** (not carried over from the filing):

The fixture is now `tests/bugs/issue-1508-transitive-link/` — `leaf.cnx` ← `mid.cnx` ← `entry.test.cnx`, exactly the three files in the body.

```
FAIL    tests/bugs/issue-1508-transitive-link/entry.test.cnx [C+CPP]
        C compile for execution failed: /usr/bin/ld: /tmp/ccaowxvB.o: in function `viaMid':
mid.c:(.text+0x9): undefined reference to `leafValue'
collect2: error: ld returned 1 exit status
```

| check | result |
| --- | --- |
| `leaf.c` contains the definition | yes — `grep -c 'uint32_t leafValue' leaf.c` → 1 |
| the three objects link by hand | **exit 0** — `gcc -std=c99 -I tests/include -I . entry.test.c mid.c leaf.c`, and the binary runs → exit 0 |
| the harness links them | no — `undefined reference` |

So the generated C is correct and complete; only the link step is short. Confirmed as filed.

**One correction to the body for whoever reads this next:** §1 cites `scripts/test-utils.ts` line 1398 for the direct-only link list. It is now **line 1499** (`const helperCnxFiles = TestUtils.findHelperCnxFiles(cnxFile, source);`); `helperClosure` is still at line 875. The line moved, the mechanism did not.

**Also worth recording:** the fixture's first run failed with `no snapshot`, not with the link error — CLAUDE.md's "mismatch masks execution". The link defect only surfaces once snapshots exist, which is a second reason a 2-hop execution fixture was unlikely to be written and diagnosed by accident.

Plan follows the DoD sections in order. Will comment as boxes land rather than ticking in a batch at the end.

**Comment by jlaustill** [comment]
## §1 lands — plus a correction to R4 and one new bug

**§1 is complete** (`5d442fb1`). The link step consumes `helperClosure` instead of `findHelperCnxFiles`.

**Mutation table** — two mutations, because one is not enough here:

| mutation | `entry.test.cnx` | `control.test.cnx` | #1491 `two-consumers` |
| --- | --- | --- | --- |
| revert to the direct list | RED `undefined reference to 'leafValue'` | RED (same signature) | RED `undefined reference to 'sharedWork'` |
| link every `.c` in the directory | RED `multiple definition of 'main'` | RED `multiple definition of 'main'` | green |
| restored | green | green | green |

The second mutation is why the control earns its place. Under mutation 1 the control reddens for the *same* reason as the reproduction — `mid.c` references `leafValue` as a whole translation unit whoever calls it — so mutation 1 alone would let "the control works" be claimed on no evidence. Mutation 2 produces a failure signature the reproduction cannot produce, which is what the acceptance actually asked for.

**Watch item from the DoD, answered:** widening the closure also widens the in-place helper re-transpile loop and the #1470 header-divergence guard. Full suite after the change: **1236 passed, 0 FAIL lines, exit 0.** No previously-invisible divergence surfaced. Unit suite: **332 files / 7223 tests, exit 0.**

**The #1491 workaround is removed** and that fixture still links — which is the proof it was a workaround, and mutation 1 reddens it, which is the proof the removal is load-bearing rather than cosmetic.

---

## R4 is already done, by #1322

This card measured `main` at `15fd3c86` (2026-09-05). #1322 merged as `e5934bc9` **after** that, and it landed **E0506** — the exact "Option A" this card poses as an open question:

```
$ npx tsx src/index.ts probe.cnx   # probe.cnx: #include "nope.cnx"
Error: probe.cnx:1:0 error[E0506]: Included C-Next file not found: nope.cnx
       help: A quoted include is resolved relative to the file it appears in (ADR-010); ...
EXIT=1
```

`tests/include/missing-cnx-include-error` already asserts it, and ADR-010's Diagnostics table already lists E0503/E0504/E0506. **R4 needs no decision and no behavior change** — only a matrix row saying it is covered.

ADR-010 also *already answers* §2's second design question. It states that the three include diagnostics occupy no matrix cell, and why: an `#include` is grammatical only before the first declaration, so it is enclosed by no scope, function or variable, and the context axis asks exactly that. That text is from #1322 too. §2 therefore inherits an answer rather than needing to invent one.

## New bug, found and fixed here

The E0506 probe printed `Warning: Warning: #include ... not found`. `ResultPrinter` prepends `Warning: ` to every entry in `ITranspilerResult.warnings`, and **seven message sources embedded it too** — IncludeResolver x3, CppEntryPointScanner x2, DependencyGraph, and `getReservedFieldWarning` (shared by both struct collectors, which is why grepping the push sites undercounts it). Users saw two formats for one concept.

Fixed in `9b419dc9`; the prefix belongs to the printer alone. Direct `console.warn` calls are untouched — they never pass through `ResultPrinter`, so they must spell their own.

Guarded by `WarningPrefixOwnership.test.ts`, mutation-checked (restoring the prefix on `DependencyGraph` reddens it and names the file:line). Nothing else could have caught this: not a type error, not a lint error, and no fixture compares warning text.

The warning is **not** redundant with E0506 and was not deleted — it still fires for a missing quoted `.h`, which E0506 does not cover (E0506 is `.cnx`-only; the `.h` case warns and exits 0).

---

Next: §2–4, the ADR-010 matrix. Note for that work — the card says only ADR-016/044/051/057/070 carry a `MATRIX-SEVERITY` table. Re-measured today: **26 ADRs do** (`grep -l 'MATRIX-SEVERITY' docs/decisions/*.md`). ADR-010 still has none, so the premise holds, but there are 25 exemplars rather than 4.

**Comment by jlaustill** [comment]
## §2–§5 land

`9e2e43d2` (matrix + provenance), `899ee301` (markers).

### §2/§4 — ADR-010 declares and occupies its matrix

```
| Context            | same file | direct | transitive |
| global variable    | -         | ok     | ok         |
| top-level function | -         | ok     | ok         |
| scope member       | -         | ok     | ok         |
| scope method       | -         | ok     | ok         |

Scope-context matrix is satisfied (26 ADR(s), 181 obligation(s))
```

**Declaring the table could not work on its own, and that was the interesting part.** When ADR-010's promise is KEPT nothing is diagnosed — the code simply compiles — so there was no source position to derive occupancy from, and all eight cells read unoccupied however many fixtures exercised them. #1241's observability gap, not a coverage gap. The tool says so itself when you declare without recording.

So the promise records where it fires, at the **use site** rather than the directive — ADR-010 now states that, since the guidance requires the ADR to say where its fixtures occupy.

**Two recording points, because a cross-file declaration is reached two ways: it is CALLED, or its TYPE is named.** A global variable cannot call anything at file scope. §2's design question asked whether to record at resolution or rely on use-site diagnostics; recorded at resolution, both spellings, one mechanism.

### §5 — mutation table

Five mutations. Each names the cells or fixtures it reddens; a mutation that reddens nothing is not evidence.

| # | mutation | result |
| --- | --- | --- |
| 1 | link list reverts to the direct includes | `entry`, `control`, #1491 `two-consumers` all RED — `undefined reference` |
| 2 | link every `.c` in the directory | `entry`, `control` RED — `multiple definition of 'main'` |
| 3 | `isCrossFileDeclaration` always false | `coverage:matrix:check` FAILS, all 8 ADR-010 cells MISSING |
| 4 | type-use recording site removed | exactly `global variable / direct` + `global variable / transitive` MISSING |
| 5 | call recording site removed | exactly `scope method / direct` MISSING |
| — | all restored | green; zero mutation markers remain, asserted by grep |

**4 and 5 are the ones that matter for the "two sites" claim.** Each site has at least one cell only it can occupy, so neither is redundant and the pair is not over-engineering. Mutation 4's result is the direct evidence that a call-only site would have forced the `global variable` row to be declared `off` — a recorded claim that an included type cannot type a global, which is false.

### §3 — 21 fixtures marked, one per pattern

One representative per pattern rather than every fixture in it: occupancy is set membership, so the second fixture exercising a pattern adds no cell the first did not, and marking all 91 local-C-header fixtures would put a marker in 91 diffs for nothing.

S1–S10, G1–G5, R1–R5 are covered. Two notes:

- **S4 needed no new marker** — `include-cnx-mixed` already includes `<stdio.h>` and `<string.h>` beside its `.cnx` includes.
- **G4 and G5 are now the same fixture.** With its redundant include removed, `two-consumers` reaches the shared library only THROUGH its two consumers — which is the definition of G5. The workaround removal turned a G4 fixture into a G5 one.

The five `.expected.error` files shift by exactly one line and nothing else: ADR-043 carries fixture comments into generated output, so a marker line moves the directive the diagnostic reports. Codes unchanged, `diagnostics:manifest:check` green.

### On running the gate

`npm test` alone reported **1238 passed / 0 failed** while `npm run test:gate` reported **3 failed** — three `tests/bugs/` fixtures whose snapshots I had not regenerated after marking them. `test:all` is four checks of thirty-two, and this is what that costs in practice. Final gate result to follow in the PR.

**Comment by jlaustill** [comment]
PR: #1540 (`fix/1508-transitive-link-closure` → `main`)

Full DoD is closed in the one PR. `npm run test:gate` — **all 32 checks passed**, including `coverage:matrix:check`, `adr:independence:check`, `diagnostics:manifest:check` and `working tree clean`.

| § | status | evidence |
| --- | --- | --- |
| 1 harness links the closure | done | `5d442fb1`; mutations 1–2; #1491 workaround removed and still links |
| 2 ADR-010 declares its matrix | done | `9e2e43d2`; per-cell justification, `same file` = `off` with its reason |
| 3 every pattern marked | done | `899ee301`; 21 fixtures, S1–S10 / G1–G5 / R1–R5 |
| 4 regenerated and gated | done | `Scope-context matrix is satisfied (26 ADR(s), 181 obligation(s))` |
| 5 mutation-checked | done | five mutations, each naming what it reddens |
| 6 rewrite test | done | `adr:independence:check` pass |

Out-of-scope items respected: no include pattern changed meaning, ADR-105 untouched, and #1402 worked around per §2 rather than fixed — the two chain fixtures live in separate directories precisely because the relationship axis measures the deepest chain from the fixture.
