### ISSUE TITLE
critical block generates __get_PRIMASK/__set_PRIMASK calls that don't compile on Teensy 4.0

### ISSUE THREAD

**Issue by jlaustill** [jlaustill/c-next#778]
## Bug
The `critical { }` block generates ADR-050 wrapper functions that call `__get_PRIMASK()` and `__set_PRIMASK()`. These CMSIS intrinsics are defined in `cmsis_gcc.h` in the Teensy 4.0 core, but **nothing in the Arduino.h include chain pulls that header in**.

## Reproducer
```c-next
#include <Arduino.h>

scope CriticalTest {
    atomic bool flag <- false;
    u8 value <- 0;

    public void safeWrite(u8 newValue) {
        critical {
            value <- newValue;
            flag <- true;
        }
    }
}
```

## Generated output (critical_test.c)
```c
static inline uint32_t __cnx_get_PRIMASK(void) { return __get_PRIMASK(); }
static inline void __cnx_set_PRIMASK(uint32_t mask) { __set_PRIMASK(mask); }
```

## Error
```
error: '__get_PRIMASK' was not declared in this scope; did you mean '__cnx_get_PRIMASK'?
error: '__set_PRIMASK' was not declared in this scope; did you mean '__cnx_set_PRIMASK'?
```

## Platform
Teensy 4.0, PlatformIO, framework-arduinoteensy, cnext v0.1.65

## Suggestion
The transpiler could emit `#include <cmsis_gcc.h>` (or equivalent) when a `critical` block is used, or use `noInterrupts()`/`interrupts()` which are available via Arduino.h on all platforms.
