### ISSUE TITLE
Array dimension naming an enum reaches the .h as source text: a third, scope-blind resolver on the parameter path

### ISSUE THREAD

**Issue by jlaustill** [jlaustill/c-next#1462]
## Summary

C-Next resolves an array dimension that names a symbol in **three** places, and one of them is scope-blind. A function parameter dimensioned by an enum reaches the `.h` as **raw C-Next source text**, while the `.c` emits the correct C identifier — so the two disagree and the header does not compile, at exit 0.

## Reproduction

`dim.cnx`:

```c-next
scope Motor {
    public enum State { IDLE, RUN, COUNT }

    public u32 sum(u8[State.COUNT] data) {
        return data[0];
    }
}
```

```console
$ npx tsx src/index.ts dim.cnx && echo "exit=$?"
exit=0
```

`dim.h` — source text, not an identifier:

```c
uint32_t Motor__sum(uint8_t data[State.COUNT]);
```

`dim.c` — correct:

```c
uint32_t Motor__sum(uint8_t data[Motor__State__COUNT]) {
```

```console
$ gcc -c -std=c11 -I. dim.c
dim.h:24:34: error: 'State' undeclared here (not in a function)
```

Note both types here are **public**, so this is not a visibility bug.

## Cause: three resolvers, one authoritative

| Site | Reads | Scope-aware? | Enum branch? |
| --- | --- | --- | --- |
| `ScopeUtils.resolveDimensionName` | injected `isKnownEnum` predicate | yes | yes |
| variable path (`HeaderSymbolAdapter.resolveArrayDimension`) | delegates to the above | yes | yes |
| **parameter path (`HeaderSymbolAdapter.resolveConstDimension`)** | **`CodeGenState.constValues` only** | **no** | **no** |

The third reads the const map and returns the dimension unchanged when it misses — which is every enum-qualified dimension. #1127 moved the rule onto `ScopeUtils` precisely so the variable path and the struct-field path would share it; the parameter path was not moved with them.

## Why now

Raised in review of #1460. That PR moves two of the three sites onto the scope-aware path, which leaves this one as the odd one out — the state CLAUDE.md's no-duplicate-paths rule is written against. It is **not** caused by #1460: `git diff main` shows the PR does not touch `resolveConstDimension`, `headerArrayDimensions` or `constValues`, and the reproduction uses only public types.

Filing so the next person does not have to rediscover which of the three is authoritative.

## Suggested fix

Route `headerArrayDimensions` through `ScopeUtils.resolveDimensionName` with the same injected `isKnownEnum` predicate the variable path uses, and keep the const-folding as a second step. Then there is one rule with one home.

## Definition of done

- [ ] One dimension-resolution rule, reached by the variable, struct-field and parameter paths
- [ ] Fixture: a public function whose parameter is dimensioned by a scope enum, asserting the `.h` and `.c` agree — and that the `.h` **compiles**
- [ ] A negative control beside it: a const-dimensioned parameter, which must still fold to its value
- [ ] Mutation-checked: point the parameter path back at the const-only resolver and confirm the fixture reddens
