### ISSUE TITLE
main does not typecheck: buildMISRA51Conflict omits IConflict's required position fields

### ISSUE THREAD

**Issue by jlaustill** [jlaustill/c-next#1347]
Current `main` (36e452c9) fails `npm run typecheck`, which `pr-checks.yml:160` runs on every PR. **Every open and future PR fails CI until this is fixed.**

## Reproduction

```
$ git checkout main && npx tsc --noEmit
src/transpiler/logic/symbols/SymbolTable.ts(993,5): error TS2739: Type '{ symbolName: string; definitions: TSymbol[]; severity: "error"; message: string; }' is missing the following properties from type 'IConflict': sourceFile, line, column
```

Verified on a clean checkout of `main` with no local changes.

## Cause — a semantic merge conflict, 28 seconds apart

| | #1342 (issue #1334), merged 05:40:19 | #1339 (issue #1307), merged 05:40:47 |
| --- | --- | --- |
| Change | Made `sourceFile` / `line` / `column` **required** on `IConflict` | Added `SymbolTable.buildMISRA51Conflict()`, returning an `IConflict` **without** them |
| Its own tree | contains no `buildMISRA51Conflict` | contains no `sourceFile` on `IConflict` |

Each PR was green on its own, and they touch different files, so git merged both
without a textual conflict. The types do not compose. Nothing was wrong with either
review; the gap is that neither branch was retested against the other's merged state.

## The fix is not just "add three fields"

#1342 made those fields required for a reason recorded in `IConflict.ts`: a conflict
reported without a real position lands at the hardcoded `1:0`, and
`FixtureOccupancy.ts:45` skips `1:0` as a known placeholder — so the diagnostic can
never occupy a scope-context matrix cell.

E0204 therefore needs the **real** position, not a filler. The data is already in
hand: `buildMISRA51Conflict` builds its `locations` string from
`symbol.sourceFile` and `symbol.sourceLine` on the same `group` it would read
from, so `group[0]` can populate all three fields.

While fixing, check whether E0204 now has a path to occupy its matrix cell, and
whether ADR-016 or ADR-051 declares an obligation that this unblocks.

## Prevention

Worth considering separately: this class of break is invisible to per-PR CI by
construction. A required check on the merge result, or a re-run of CI on `main`
after each merge, is what would have caught it.

**Comment by jlaustill** [comment]
Duplicate of #1345, which landed the fix in 006a7bf6 before I filed this. Verified on the current `main`:

```
$ npx tsc --noEmit && echo CLEAN
CLEAN
```

Closing as a duplicate. The one item here not covered by #1345 is the prevention note — per-PR CI cannot see this class of break by construction, since each PR was green against a `main` that did not yet contain the other. If that is worth pursuing it should be its own issue rather than a reopened duplicate.
