### ISSUE TITLE
Seven cross-file fixtures share one generated helper, so parallel workers race and link against a partial types.c

### ISSUE THREAD

**Issue by jlaustill** [jlaustill/c-next#1308]
## Summary

`tests/enum/cross-file-struct-member/` holds **seven** fixtures that all `#include
"types.cnx"`, so all seven regenerate and link against the *same* `types.c`/`types.h`.
`scripts/test.ts` runs 24 workers in parallel, so one worker can be regenerating those
shared helpers while another is compiling or linking against them.

Observed once in a full `npm run test:q`:

```
FAIL    tests/enum/cross-file-struct-member/cross-file-enum-global-prefix.test.cnx
        C compile for execution failed:
/usr/bin/ld: cross-file-enum-global-prefix.expected.c:(.text+0xa):
             undefined reference to `config'
/usr/bin/ld: warning: relocation against `config' in read-only section `.text'
1106/1107 tests passed, 1 failed
```

`config` is defined in `types.cnx`. An immediately following full run passed 1107/1107, and
the same fixture passes in isolation, with no tracked file differing
(`git status --porcelain tests/` → 0). So the input was identical and the outcome was not.

## Why it is a shared-helper race, not a codegen defect

The seven fixtures in that directory share two generated helpers:

```
types.cnx  -> types.c, types.h
math-utils.cnx -> math-utils.c, math-utils.h
```

Nothing serialises the workers that own them. A truncated or mid-write `types.c` links as
"undefined reference" to every symbol after the truncation point, which is exactly the
observed shape — and it is not reproducible on demand, which is why it has probably been
dismissed as noise before.

## Why it matters beyond one red run

The project's own notes already treat intermittent CI failures as "resource contention,
re-run fixes them". That is true here and it is the problem: a real regression in a
cross-file fixture would look exactly like this and be re-run away. A flake in the
**cross-file** fixtures is the worst place to have one, because per CLAUDE.md 35 of 37
error codes have no cross-file coverage at all — these are among the few that do.

## Suggested fix

Any of:

1. Give each fixture its own helper copy, so no two workers share an output path.
2. Serialise fixtures that share a helper — group by resolved include set and run each
   group on one worker.
3. Generate helpers once, up front, before the parallel phase starts, and make the workers
   read-only for shared outputs.

(3) is closest to what the runner already assumes.

Verification for a fix: run `npm run test:q` in a loop (say 20 iterations) and require
1107/1107 every time. A single green run cannot distinguish "fixed" from "did not happen to
race", which is the same trap as a mutation table that was never checked.

Found while wiring #1285 PR4; the failure initially looked like a regression from that
change, and ruling it out cost a stash-and-bisect against `main`.
